- name: golang setting
  hosts: my_server
  become: yes
  user: kouf
  tasks:
      - name: golang install
        yum:
            name: golang
            state: present

      - name: golang update
        yum:
            name: golang
            state: latest
