- hosts: my_server
  become: yes
  user: kouf
  tasks:
      - name: Add Remi
        command: rpm {{ item }} creates=/etc/yum.repos.d/remi.repo
        with_items:
            - -Uvh https://rpms.remirepo.net/enterprise/remi-release-7.rpm

      - name: update yum
        yum:
            state: latest

      - name: Add Remi-PHP
        yum: 
            name: ['php', 'php-fpm']
            enablerepo: remi,remi-php73,epel
            state: present
