- hosts: my_server
  become: yes
  user: kouf
  tasks:
      - name: Add EPEL
        yum: name=epel-release state=present

      - name: Add ELRepo
        command: rpm {{ item }} creates=/etc/yum.repos.d/elrepo.repo
        with_items:
            - --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
            - -Uvh https://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm

      - name: Add Remi
        yum:
            name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm

      - name: Update yum
        yum: 
            state: latest
